export const initialValues = {
  status: "",
  number: "",
  class: "",
  subject: "",
  court: "",
  division: "",
  divisionPhone: "",
  divisionEmail: "",
  distribution: "",
  control: "",
  area: "",
  price: "",
  tribunal: "",
  others: "",
  judge: "",
  exeqte: "",
  customerId: "",
  exectdo: "",
  extra: "",
};
