export const customersInitial = {
    cnae: "",
    cpf: "",
    rg: "",
    name: "",
    gender: "",
    email: "",
    phone1: "",
    phone2: "",
    nationality: "",
    document: "",
    postalCode: "",
    street: "",
    number: "",
    complement: "",
    neighborhood: "",
    city: "",
    state: "",
    country: "Brasil",
    corporateName: "",
    businessPostalCode: "",
    businessStreet: "",
    businessNumber: "",
    businessComplement: "",
    businessNeighborhood: "",
    businessCity: "",
    businessState: "",
  };
  